from dataclasses import dataclass
from typing import List, Tuple


@dataclass(frozen=True)
class Attraction:
    name: str
    category: str
    estimated_cost: int
    safety_score: int  # 1-10
    emotion_suitability_tags: Tuple[str, ...]
    region: str


SRI_LANKA_ATTRACTIONS: List[Attraction] = [
    Attraction(
        name="Hikkaduwa Beach",
        category="beach",
        estimated_cost=45,
        safety_score=8,
        emotion_suitability_tags=("happy", "surprise", "neutral"),
        region="South Coast",
    ),
    Attraction(
        name="Sigiriya Rock Fortress",
        category="cultural",
        estimated_cost=60,
        safety_score=9,
        emotion_suitability_tags=("fear", "surprise", "neutral"),
        region="Cultural Triangle",
    ),
    Attraction(
        name="Nuwara Eliya Tea Estates",
        category="nature",
        estimated_cost=40,
        safety_score=9,
        emotion_suitability_tags=("sad", "neutral", "disgust"),
        region="Hill Country",
    ),
    Attraction(
        name="Yala National Park",
        category="wildlife",
        estimated_cost=85,
        safety_score=8,
        emotion_suitability_tags=("surprise", "happy", "fear"),
        region="South East",
    ),
    Attraction(
        name="Udawalawe National Park",
        category="wildlife",
        estimated_cost=70,
        safety_score=9,
        emotion_suitability_tags=("angry", "neutral", "disgust"),
        region="Sabaragamuwa",
    ),
    Attraction(
        name="Kandy Temple and Gardens",
        category="cultural",
        estimated_cost=35,
        safety_score=9,
        emotion_suitability_tags=("sad", "neutral", "fear"),
        region="Central Province",
    ),
    Attraction(
        name="Ella Scenic Trails",
        category="nature",
        estimated_cost=30,
        safety_score=8,
        emotion_suitability_tags=("sad", "angry", "happy", "neutral"),
        region="Uva Province",
    ),
    Attraction(
        name="Bentota Water Sports",
        category="adventure",
        estimated_cost=75,
        safety_score=7,
        emotion_suitability_tags=("happy", "surprise", "angry"),
        region="South West Coast",
    ),
    Attraction(
        name="Madu River Boat Safari",
        category="nature",
        estimated_cost=25,
        safety_score=8,
        emotion_suitability_tags=("neutral", "sad", "fear"),
        region="Southern Province",
    ),
    Attraction(
        name="Galle Fort Heritage Walk",
        category="cultural",
        estimated_cost=20,
        safety_score=9,
        emotion_suitability_tags=("angry", "neutral", "sad"),
        region="Southern Province",
    ),
    Attraction(
        name="Arugam Bay Surf Point",
        category="adventure",
        estimated_cost=55,
        safety_score=7,
        emotion_suitability_tags=("surprise", "happy"),
        region="Eastern Province",
    ),
    Attraction(
        name="Sinharaja Rainforest Reserve",
        category="nature",
        estimated_cost=50,
        safety_score=8,
        emotion_suitability_tags=("disgust", "fear", "neutral"),
        region="Sabaragamuwa",
    ),
    Attraction(
        name="Colombo City Highlights",
        category="cultural",
        estimated_cost=35,
        safety_score=8,
        emotion_suitability_tags=("neutral", "happy", "surprise"),
        region="Western Province",
    ),
    Attraction(
        name="Horton Plains National Park",
        category="nature",
        estimated_cost=52,
        safety_score=8,
        emotion_suitability_tags=("sad", "neutral", "fear", "surprise"),
        region="Hill Country",
    ),
    Attraction(
        name="Dambulla Cave Temples",
        category="cultural",
        estimated_cost=42,
        safety_score=9,
        emotion_suitability_tags=("surprise", "neutral", "fear"),
        region="Cultural Triangle",
    ),
    Attraction(
        name="Mirissa Whale & Beach",
        category="beach",
        estimated_cost=68,
        safety_score=7,
        emotion_suitability_tags=("happy", "surprise", "neutral"),
        region="South Coast",
    ),
    Attraction(
        name="Kitulgala Rafting & Jungle",
        category="adventure",
        estimated_cost=72,
        safety_score=7,
        emotion_suitability_tags=("happy", "surprise", "fear"),
        region="Sabaragamuwa",
    ),
    Attraction(
        name="Knuckles Mountain Range",
        category="nature",
        estimated_cost=48,
        safety_score=7,
        emotion_suitability_tags=("angry", "sad", "neutral"),
        region="Central Province",
    ),
    Attraction(
        name="Polonnaruwa Ancient City",
        category="cultural",
        estimated_cost=38,
        safety_score=8,
        emotion_suitability_tags=("fear", "surprise", "neutral"),
        region="North Central Province",
    ),
    Attraction(
        name="Minneriya National Park",
        category="wildlife",
        estimated_cost=58,
        safety_score=8,
        emotion_suitability_tags=("sad", "happy", "neutral"),
        region="North Central Province",
    ),
    Attraction(
        name="Anuradhapura Sacred City",
        category="cultural",
        estimated_cost=32,
        safety_score=8,
        emotion_suitability_tags=("fear", "neutral", "sad"),
        region="North Central Province",
    ),
    Attraction(
        name="Ritigala Forest Monastery",
        category="nature",
        estimated_cost=28,
        safety_score=8,
        emotion_suitability_tags=("angry", "sad", "fear", "neutral"),
        region="North Central Province",
    ),
    Attraction(
        name="Adams Peak Sunrise Trek",
        category="adventure",
        estimated_cost=44,
        safety_score=7,
        emotion_suitability_tags=("fear", "sad", "surprise", "neutral"),
        region="Central Province",
    ),
    Attraction(
        name="Udawattekele Sanctuary",
        category="nature",
        estimated_cost=18,
        safety_score=9,
        emotion_suitability_tags=("disgust", "sad", "neutral"),
        region="Central Province",
    ),
    Attraction(
        name="Diyaluma Falls Excursion",
        category="nature",
        estimated_cost=36,
        safety_score=7,
        emotion_suitability_tags=("sad", "disgust", "neutral"),
        region="Uva Province",
    ),
    Attraction(
        name="Trincomalee Coastal Relaxation",
        category="beach",
        estimated_cost=46,
        safety_score=7,
        emotion_suitability_tags=("disgust", "happy", "neutral"),
        region="Eastern Province",
    ),
    Attraction(
        name="Koggala Lake Canoeing",
        category="nature",
        estimated_cost=32,
        safety_score=8,
        emotion_suitability_tags=("disgust", "neutral", "sad"),
        region="Southern Province",
    ),
    Attraction(
        name="Tangalle Sunset Coast",
        category="beach",
        estimated_cost=26,
        safety_score=8,
        emotion_suitability_tags=("angry", "sad", "neutral"),
        region="Southern Province",
    ),
    Attraction(
        name="Kalutara Beach Calm",
        category="beach",
        estimated_cost=22,
        safety_score=8,
        emotion_suitability_tags=("angry", "neutral", "sad"),
        region="Western Province",
    ),
    Attraction(
        name="Pigeon Island Snorkeling",
        category="adventure",
        estimated_cost=82,
        safety_score=7,
        emotion_suitability_tags=("surprise", "happy"),
        region="Eastern Province",
    ),
    Attraction(
        name="Peradeniya Botanical Gardens",
        category="nature",
        estimated_cost=22,
        safety_score=9,
        emotion_suitability_tags=("sad", "neutral", "disgust"),
        region="Central Province",
    ),
]
